---
  services:
    - docker

  env:
    IMAGE_NAME: "test"

  before_script:
    - docker build -t ${IMAGE_NAME} ./tests/

  script:
    - docker run -d --privileged -v $(pwd):/operator --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -w /operator -e TERM=xterm --tty ${IMAGE_NAME} bash
    - docker exec --tty $(docker ps -l -q) ./install.sh

  after_script:
    - docker stop -t 0 $(docker ps -l -q)
    - docker rm $(docker ps -l -q)
    - docker rmi ${IMAGE_NAME}
