---
  project_name: "operator"
  project_folder: "../../"
  source_folder: "{{ project_folder }}/web_interface"
  project_tmp_folder: "/var/{{ project_name }}/tmp"
  tmp_folder_mode: "0700"
  tmp_folder_owner: "www-data"

  operator_db_name: "operator"
  operator_db_user: "operator"
  # operator_db_password: "password"
  operator_db_scheme_file: "{{ source_folder }}/conf/operator.sql"

  configuration_templates:
    - "{{ source_folder }}/conf/main_conf.php"

  admin_users:
    - login: "user1"
      pass: "pass1"
      is_admin: true
    - login: "user2"
      pass: "pass2"
