---
project_name: "operator"
project_folder: "../../"
source_folder: "{{ project_folder }}/source"

asterisk_db_name: "asterisk"
asterisk_db_user: "asterisk"
# asterisk_db_password: "password"
asterisk_db_scheme_file: "{{ source_folder }}/conf/asterisk.sql"

asterisk_packages:
  - "asterisk"

asterisk_config_folder: "/etc/asterisk"
asterisk_modules_config: "{{ asterisk_config_folder }}/modules.conf"
