---
  - name: "Creating tmp folder for project: {{ project_tmp_folder }}."
    file:
      path: "{{ project_tmp_folder }}"
      state: directory
      mode: "{{ tmp_folder_mode }}"
      owner: "{{ tmp_folder_owner }}"

  - name: "Checking tmp folder's mode."
    stat:
      path: "{{ project_tmp_folder }}"
    register: tmp_folder
    failed_when: tmp_folder.stat.mode != tmp_folder_mode

  - name: "Generating configuration files from tempplates."
    template:
      src: "{{ item | basename }}.j2"
      dest: "{{ item }}"
    with_items: "{{ configuration_templates }}"

  - name: "Restoring operator DB scheme."
    mysql_db:
      name: "{{ operator_db_name }}"
      login_user: "{{ operator_db_user }}"
      login_password: "{{ operator_db_password }}"
      state: import
      target: "{{ operator_db_scheme_file }}"
