---
  - name: "Loading Asterisk DB scheme."
    mysql_db:
      name: "{{ asterisk_db_name }}"
      login_user: "{{ asterisk_db_user }}"
      login_password: "{{ asterisk_db_password }}"
      state: import
      target: "{{ asterisk_db_scheme_file }}"
    tags: ["asterisk"]

  - name: "Installing packages."
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ asterisk_packages }}"
    tags: ["asterisk"]

  - name: "Disable pbx_ael.so module."
    lineinfile:
      path: "{{ asterisk_modules_config }}"
      line: "noload => pbx_ael.so"
      insertbefore: "[global]"
      state: present
      backup: yes
    tags: ["asterisk"]

  - name: "Generating asterisk configuration files."
    template:
      src: "{{ item | basename }}.j2"
      dest: "{{ item }}"
    with_items:
      - "/etc/asterisk/sip.conf"

  - name: "Restart IP-PBX Asterisk."
    service:
      name: "asterisk"
      state: restarted
    tags: ["asterisk"]
